/* AUTO-GENERATED — verified shrine metadata (type / reward / quest).
   Sourced from community wikis by a 20-agent workflow (10 gather + 10 cross-verify);
   118/120 types independently agreed across two sources. Raw: _cache/shrinedata_raw.json. */
window.SHRINEDATA = {
  "Akh Va'quot Shrine": {"type": "Puzzle", "reward": "Feathered Spear"},
  "Bareeda Naag Shrine": {"type": "Puzzle", "reward": "Royal Bow"},
  "Bosh Kala Shrine": {"type": "Puzzle", "reward": "Soldier's Claymore"},
  "Chaas Qeta Shrine": {"type": "Major Test of Strength", "reward": "Climbing Gear"},
  "Daag Chokah Shrine": {"type": "Blessing", "reward": "Ancient Core", "quest": "The Lost Pilgrimage"},
  "Dagah Keek Shrine": {"type": "Blessing", "reward": "Silver Rupee", "quest": "The Ceremonial Song"},
  "Dah Hesho Shrine": {"type": "Minor Test of Strength", "reward": "Giant Ancient Core"},
  "Dah Kaso Shrine": {"type": "Minor Test of Strength", "reward": "Ancient Core"},
  "Daka Tuss Shrine": {"type": "Puzzle", "reward": "Silver Longsword"},
  "Dako Tah Shrine": {"type": "Puzzle", "reward": "Radiant Shield", "quest": "The Eye of the Sandstorm"},
  "Daqa Koh Shrine": {"type": "Puzzle", "reward": "Silver Rupee"},
  "Daqo Chisay Shrine": {"type": "Puzzle", "reward": "Thunderblade"},
  "Dila Maag Shrine": {"type": "Blessing", "reward": "Barbarian Armor", "quest": "The Desert Labyrinth"},
  "Dow Na'eh Shrine": {"type": "Puzzle", "reward": "Zora Sword"},
  "Dunba Taag Shrine": {"type": "Puzzle", "reward": "Great Thunderblade"},
  "Gee Ha'rah Shrine": {"type": "Puzzle", "reward": "Diamond"},
  "Goma Asaagh Shrine": {"type": "Major Test of Strength", "reward": "Royal Claymore"},
  "Gorae Torr Shrine": {"type": "Blessing", "reward": "Great Frostblade", "quest": "The Gut Check Challenge"},
  "Ha Dahamar Shrine": {"type": "Puzzle"},
  "Hawa Koth Shrine": {"type": "Puzzle", "reward": "Gold Rupee"},
  "Hia Miu Shrine": {"type": "Major Test of Strength", "reward": "Sapphire"},
  "Hila Rao Shrine": {"type": "Puzzle", "reward": "Opal", "quest": "Watch Out for the Flowers"},
  "Ishto Soh Shrine": {"type": "Puzzle", "reward": "Ancient Core"},
  "Ja Baij Shrine": {"type": "Tutorial", "reward": "Traveler's Claymore"},
  "Jee Noh Shrine": {"type": "Puzzle", "reward": "Opal"},
  "Jitan Sa'mi Shrine": {"type": "Blessing", "reward": "Frostspear", "quest": "The Spring of Wisdom"},
  "Joloo Nah Shrine": {"type": "Puzzle", "reward": "Golden Claymore", "quest": "Test of Will"},
  "Ka'o Makagh Shrine": {"type": "Puzzle", "reward": "Traveler's Bow"},
  "Kaam Ya'tak Shrine": {"type": "Puzzle", "reward": "Edge of Duality"},
  "Kah Mael Shrine": {"type": "Puzzle", "reward": "Diamond"},
  "Kah Okeo Shrine": {"type": "Puzzle", "reward": "Forest Dweller's Sword"},
  "Kah Yah Shrine": {"type": "Puzzle", "reward": "Knight's Claymore", "quest": "A Fragmented Monument"},
  "Kam Urog Shrine": {"type": "Puzzle", "reward": "Soldier's Spear", "quest": "The Cursed Statue"},
  "Katah Chuki Shrine": {"type": "Minor Test of Strength", "reward": "Royal Halberd"},
  "Katosa Aug Shrine": {"type": "Puzzle", "reward": "Great Frostblade"},
  "Kay Noh Shrine": {"type": "Puzzle", "reward": "Gerudo Scimitar"},
  "Kaya Wan Shrine": {"type": "Puzzle", "reward": "Knight's Broadsword"},
  "Kayra Mah Shrine": {"type": "Puzzle", "reward": "Bomb Arrows"},
  "Ke'nai Shakah Shrine": {"type": "Modest Test of Strength", "reward": "Sapphire"},
  "Keeha Yoog Shrine": {"type": "Blessing", "reward": "Diamond", "quest": "Cliffside Etchings"},
  "Keh Namut Shrine": {"type": "Tutorial", "reward": "Traveler's Spear"},
  "Kema Kosassa Shrine": {"type": "Major Test of Strength", "reward": "Silver Rupee"},
  "Kema Zoos Shrine": {"type": "Puzzle", "reward": "Moonlight Scimitar", "quest": "The Silent Swordswomen"},
  "Keo Ruug Shrine": {"type": "Puzzle", "reward": "Knight's Claymore"},
  "Ketoh Wawai Shrine": {"type": "Blessing", "reward": "Ancient Core", "quest": "Shrouded Shrine"},
  "Korgu Chideh Shrine": {"type": "Blessing", "reward": "Gold Rupee", "quest": "Stranded on Eventide"},
  "Korsh O'hu Shrine": {"type": "Blessing", "reward": "Flamespear", "quest": "The Seven Heroines"},
  "Kuh Takkar Shrine": {"type": "Puzzle", "reward": "Frostblade"},
  "Kuhn Sidajj Shrine": {"type": "Blessing", "reward": "Giant Ancient Core", "quest": "Trial of Second Sight"},
  "Lakna Rokee Shrine": {"type": "Blessing", "reward": "Edge of Duality", "quest": "The Stolen Heirloom"},
  "Lanno Kooh Shrine": {"type": "Blessing", "reward": "Gold Rupee"},
  "Maag Halan Shrine": {"type": "Blessing", "reward": "Giant Ancient Core", "quest": "The Test of Wood"},
  "Maag No'rah Shrine": {"type": "Blessing"},
  "Maka Rah Shrine": {"type": "Puzzle", "reward": "Diamond", "quest": "Steady Thy Heart"},
  "Mezza Lo Shrine": {"type": "Puzzle", "reward": "Thunderblade", "quest": "The Crowned Beast"},
  "Mijah Rokee Shrine": {"type": "Modest Test of Strength", "reward": "Frostblade", "quest": "Under a Red Moon"},
  "Mirro Shaz Shrine": {"type": "Puzzle", "reward": "Giant Ancient Core"},
  "Misae Suma Shrine": {"type": "Blessing", "reward": "Diamond", "quest": "The Perfect Drink"},
  "Mo'a Keet Shrine": {"type": "Puzzle", "reward": "Knight's Broadsword"},
  "Mogg Latan Shrine": {"type": "Puzzle", "reward": "Forest Dweller's Spear"},
  "Monya Toma Shrine": {"type": "Puzzle", "reward": "Thunderblade"},
  "Mozo Shenno Shrine": {"type": "Major Test of Strength", "reward": "Diamond", "quest": "The Bird in the Mountains"},
  "Muwo Jeem Shrine": {"type": "Modest Test of Strength", "reward": "Royal Bow"},
  "Myahm Agana Shrine": {"type": "Puzzle", "reward": "Phrenic Bow"},
  "Namika Ozz Shrine": {"type": "Modest Test of Strength", "reward": "Frostspear"},
  "Ne'ez Yohma Shrine": {"type": "Puzzle", "reward": "Zora Spear"},
  "Noya Neha Shrine": {"type": "Minor Test of Strength", "reward": "Knight's Shield"},
  "Oman Au Shrine": {"type": "Tutorial", "reward": "Traveler's Bow"},
  "Owa Daim Shrine": {"type": "Tutorial", "reward": "Traveler's Shield"},
  "Pumaag Nitae Shrine": {"type": "Minor Test of Strength", "reward": "Boomerang"},
  "Qaza Tokki Shrine": {"type": "Blessing", "reward": "Barbarian Leg Wraps", "quest": "Trial on the Cliff"},
  "Qua Raym Shrine": {"type": "Puzzle", "reward": "Knight's Claymore"},
  "Qukah Nata Shrine": {"type": "Blessing", "reward": "Rubber Tights", "quest": "A Song of Storms"},
  "Raqa Zunzo Shrine": {"type": "Blessing", "reward": "Radiant Shield", "quest": "The Undefeated Champ"},
  "Ree Dahee Shrine": {"type": "Puzzle", "reward": "Climber's Bandana"},
  "Rin Oyaa Shrine": {"type": "Puzzle", "reward": "Ancient Core"},
  "Ritaag Zumo Shrine": {"type": "Blessing", "reward": "Giant Ancient Core", "quest": "Into the Vortex"},
  "Rok Uwog Shrine": {"type": "Puzzle", "reward": "Drillshaft"},
  "Rona Kachta Shrine": {"type": "Blessing", "reward": "Great Flameblade"},
  "Rota Ooh Shrine": {"type": "Puzzle", "reward": "Feathered Edge"},
  "Rucco Maag Shrine": {"type": "Puzzle", "reward": "Silver Bow"},
  "Saas Ko'sah Shrine": {"type": "Major Test of Strength", "reward": "Flameblade"},
  "Sah Dahaj Shrine": {"type": "Puzzle", "reward": "Knight's Bow"},
  "Sasa Kai Shrine": {"type": "Modest Test of Strength", "reward": "Frostblade", "quest": "Sign of the Shadow"},
  "Sha Gehma Shrine": {"type": "Puzzle", "reward": "Royal Broadsword"},
  "Sha Warvo Shrine": {"type": "Puzzle", "reward": "Knight's Bow"},
  "Shada Naw Shrine": {"type": "Puzzle", "reward": "Great Frostblade"},
  "Shae Katha Shrine": {"type": "Blessing", "reward": "Thunderspear", "quest": "The Serpent's Jaws"},
  "Shae Loya Shrine": {"type": "Puzzle", "reward": "Falcon Bow"},
  "Shae Mo'sah Shrine": {"type": "Puzzle", "reward": "Stone Smasher"},
  "Shai Utoh Shrine": {"type": "Puzzle", "reward": "Traveler's Sword"},
  "Shai Yota Shrine": {"type": "Blessing", "reward": "Great Flameblade", "quest": "Master of the Wind"},
  "Shee Vaneer Shrine": {"type": "Puzzle", "reward": "Eightfold Longblade"},
  "Shee Venath Shrine": {"type": "Puzzle", "reward": "Serpentine Spear"},
  "Sheem Dagoze Shrine": {"type": "Puzzle", "reward": "Great Thunderblade", "quest": "The Two Rings"},
  "Sheh Rata Shrine": {"type": "Puzzle", "reward": "Giant Boomerang"},
  "Sho Dantu Shrine": {"type": "Puzzle", "reward": "Silver Rupee"},
  "Shoda Sah Shrine": {"type": "Puzzle", "reward": "Five Ice Arrows"},
  "Shoqa Tatone Shrine": {"type": "Modest Test of Strength", "reward": "Royal Broadsword", "quest": "Guardian Slideshow"},
  "Shora Hah Shrine": {"type": "Puzzle", "reward": "Great Flameblade"},
  "Soh Kofi Shrine": {"type": "Minor Test of Strength", "reward": "Knight's Bow"},
  "Suma Sahma Shrine": {"type": "Blessing", "reward": "Moonlight Scimitar", "quest": "Secret of the Snowy Peaks"},
  "Ta'loh Naeg Shrine": {"type": "Combat", "reward": "Eightfold Blade"},
  "Tah Muhl Shrine": {"type": "Puzzle", "reward": "Cobble Crusher"},
  "Tahno O'ah Shrine": {"type": "Blessing", "reward": "Climbing Boots", "quest": "Secret of the Cedars"},
  "Tawa Jinn Shrine": {"type": "Blessing", "reward": "Great Thunderblade", "quest": "The Three Giant Brothers"},
  "Tena Ko'sah Shrine": {"type": "Major Test of Strength", "reward": "Knight's Halberd"},
  "Tho Kayu Shrine": {"type": "Blessing", "reward": "Golden Bow"},
  "To Quomo Shrine": {"type": "Blessing", "reward": "Royal Claymore"},
  "Toh Yahsa Shrine": {"type": "Puzzle", "reward": "Rubber Armor", "quest": "Trial of Thunder"},
  "Toto Sah Shrine": {"type": "Puzzle", "reward": "Shield of the Mind's Eye"},
  "Tu Ka'loh Shrine": {"type": "Blessing", "reward": "Barbarian Helm", "quest": "Trial of the Labyrinth"},
  "Tutsuwa Nima Shrine": {"type": "Major Test of Strength", "reward": "Flamespear", "quest": "The Spring of Power"},
  "Voo Lota Shrine": {"type": "Puzzle", "reward": "Flameblade", "quest": "Recital at Warbler's Nest"},
  "Wahgo Katta Shrine": {"type": "Puzzle", "reward": "Amber"},
  "Ya Naga Shrine": {"type": "Puzzle", "reward": "Eightfold Blade"},
  "Yah Rin Shrine": {"type": "Puzzle", "reward": "Knight's Broadsword"},
  "Zalta Wa Shrine": {"type": "Puzzle", "reward": "Knight's Bow"},
  "Ze Kasho Shrine": {"type": "Puzzle", "reward": "Silverscale Spear"},
  "Zuna Kai Shrine": {"type": "Blessing", "reward": "Flameblade", "quest": "The Skull's Eye"},
};
